### ISSUE TITLE
Doesn't detect when merge conflict is not fully resolved.

### ISSUE THREAD

**Issue by amyschoen** [githubtraining/managing-merge-conflicts#27] opened 2020-02-05 17:38 UTC
## Bug Report

**Current behavior**
I only removed some of the markers for the merge conflict.  It still considered the merge conflict resolution successful.

**Reproduction**
Steps to reproduce the behavior in the course:
1. Take the course using the UI option through Step 3: Resolve more complex conflicts
2. Delete the lines with `>` and `<` from the merge conflict but leave in the `=======` lines
3. The step is considered to be completed successfully.

**Expected behavior**
I would expect it to detect that all markers have not been removed and have the student fix it.

**Possible solution**
If you have suggestions, we'd love to hear them. If not, that's ok too.

**Additional context**
GHES v2.19.6, LL v0.5.0

/cc @crichID @brianamarie @hectorsector @JasonEtco

**Comment by a-a-ron** [comment] 2020-07-28 03:50
I agree, the ideal expected behavior should detect any remaining conflict markers and point those out to the learner, but I wouldn't classify this as a bug but rather an enhancement to the ideal behavior as far as the course goes.

However, the GitHub UI isn't detecting the `======` as a conflict marker and it allows you to resolve the conflict in the UI with it remaining. This is a larger bug that affects github.com.

**Comment by amyschoen** [comment] 2020-07-28 13:19
Interesting.  I assumed it wasn't working correctly, but it's hard to fault LL if GH doesn't detect it either.

**Comment by brianamarie** [comment] 2020-07-29 08:59
Because this reflects a bug with GitHub.com and not a direct bug of this course, I'm going to close this issue. Please reopen if there is more information about why we should update this course to address this. 😊

**Closed by brianamarie** 2020-07-29 08:59 UTC
Labels: enhancement

**Comment by amyschoen** [comment] 2020-07-29 13:52
Fine by me.  It doesn't make sense to do any updates until the bug is fixed.
